name: Run Sample workflow to test SelfHosted Runner

on:
  push:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: self-hosted
    container:
      image: tiicrc/claasp-github-runner:20231004
      credentials:
        username: devopscrc
        password: ${{  secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Check Process Limits
      run: ulimit -a

    - name: add some sleep
      run: |
            echo hello world
            sleep 86400

